services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh","/wait-for-it.sh", "db:3306", "--", "./api-rest"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=mydatabasecc 

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydatabasecc
    ports:
      - "3307:3306"
    volumes:
      - ./bd_cc:/docker-entrypoint-initdb.d
